---
resources:
- name: kube-app
  type: git
  source:
    uri: https://github.com/etcinitd/kube-pipe-demo.git

jobs:
- name: build-app
  public: true
  plan:
  - get: kube-app
    trigger: true
  - task: web-app-tests
    config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang, tag: 1.6-alpine}
        inputs:
        - name: kube-app
          path: /app
        run:
          path: /app/pipeline-resources/build.sh
